In [2]:
import pandas as pd
import os
from fredapi import Fred
fred = Fred(api_key = os.getenv("FRED_API_KEY"))

In [4]:
interest_rate = fred.get_series('FEDFUNDS')
mortgage_rate = fred.get_series('MORTGAGE30US')
#consumption = fred.get_series('PCEC96')
#investments = fred.get_series('PNFIC1')
unemployment_rate = fred.get_series('UNRATE')
payrolls = fred.get_series('PAYEMS')
labor_turnover = fred.get_series('JTSJOL')
cpi = fred.get_series('CPIAUCSL')
cepi = fred.get_series('DPCCRV1Q225SBEA')
ppi = fred.get_series('PPIACO')
retail_sales = fred.get_series('MRTSSM44000USS')
personal_income = fred.get_series('PI')
personal_saving = fred.get_series('PMSAVE')
personal_spending = fred.get_series('PCE')
housing_starts = fred.get_series('MSPNHSUS')
gdp = fred.get_series('GDP')
industrial_prod = fred.get_series('INDPRO')
#nfci = fred.get_series('NFCICREDIT')
money_stock = fred.get_series('M1REAL')
#bank_lending = fred.get_series('TOTLL')
trade_balance = fred.get_series('BOPGSTB')
exports = fred.get_series('NETEXP')
imports = fred.get_series('IMPGS')
consumer_sentiment = fred.get_series('UMCSENT')
vehicle_sales = fred.get_series('TOTALSA')

In [5]:
df = pd.concat([interest_rate, unemployment_rate, payrolls, labor_turnover, cpi, cepi, ppi, retail_sales, personal_income, personal_saving, personal_spending, housing_starts, gdp, industrial_prod, money_stock, trade_balance, exports, imports, consumer_sentiment, vehicle_sales], axis =1)
df.columns = ['interest_rate', 'unemployment_rate', 'payrolls', 'labor_turnover','cpi', 'cepi', 'ppi', 'retail_sales', 'personal_income', 'personal_saving', 'personal_spending', 'housing_starts', 'gdp','industrial_prod','money_stock', 'trade_balance', 'exports', 'imports', 'consumer_sentiment', 'vehicle_sales']
df=df.dropna()
df.describe()

,interest_rate,unemployment_rate,payrolls,labor_turnover,cpi,cepi,ppi,retail_sales,personal_income,personal_saving,personal_spending,housing_starts,gdp,industrial_prod,money_stock,trade_balance,exports,imports,consumer_sentiment,vehicle_sales
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,1.800204,5.775510,140258.142857,5455.867347,233.619020,2.107143,191.485612,385831.591837,15158.920408,814.702041,12073.143878,282167.346939,17921.742980,97.501022,2090.224490,-50989.010204,-631.103092,2692.260633,81.687755,15.940939
std,1.892918,2.059279,8884.584820,2331.179648,38.667732,1.190361,36.558757,108116.164369,4758.082091,754.438727,3649.643364,78330.452236,5388.463691,5.065853,2251.620098,15497.455144,173.094220,761.371303,12.792985,2.323525
min,0.050000,3.400000,129802.000000,2232.000000,175.600000,-0.800000,128.500000,247336.000000,8940.900000,128.900000,6987.400000,171300.000000,10470.231000,84.681200,624.500000,-130273.000000,-1245.141000,1323.208000,51.500000,8.944000
25%,0.140000,4.225000,132437.500000,3738.500000,204.053750,1.400000,167.375000,307732.000000,11702.350000,430.825000,9564.925000,222500.000000,14257.047250,93.576925,701.075000,-61064.250000,-768.013000,2217.040250,71.725000,15.120000
50%,1.150000,5.200000,137703.000000,4619.500000,231.738000,1.800000,192.850000,360378.000000,14012.050000,703.600000,11266.750000,259600.000000,16688.438000,98.871950,1074.800000,-46574.000000,-567.793500,2751.570000,82.650000,16.597000
75%,3.007500,6.475000,147055.500000,7000.750000,254.617750,2.475000,204.175000,434938.000000,18219.750000,914.350000,14084.225000,322775.000000,21063.166750,101.583925,1486.025000,-40186.250000,-513.413750,3082.680250,92.850000,17.301000
max,5.980000,14.800000,159433.000000,11881.000000,320.321000,6.100000,272.274000,623521.000000,25823.500000,5981.600000,20622.300000,460300.000000,30331.117000,103.929700,7262.800000,-29678.000000,-358.368000,4511.554000,103.800000,22.055000

In [6]:
df

,interest_rate,unemployment_rate,payrolls,labor_turnover,cpi,cepi,ppi,retail_sales,personal_income,personal_saving,personal_spending,housing_starts,gdp,industrial_prod,money_stock,trade_balance,exports,imports,consumer_sentiment,vehicle_sales
2001-01-01,5.98,4.2,132703.0,5234.0,175.600,2.6,140.000,247339.0,8940.9,344.7,6987.4,171300.0,10470.231,91.8908,624.5,-35202.0,-402.653,1499.464,94.7,17.652
2001-04-01,4.80,4.4,132457.0,4615.0,176.400,1.5,136.400,249113.0,9008.9,369.3,7004.2,175200.0,10599.000,90.7384,633.0,-30521.0,-364.015,1422.028,88.4,16.872
2001-07-01,3.77,4.6,132171.0,4447.0,177.400,1.0,133.400,247336.0,9014.6,426.4,7082.3,175000.0,10598.020,89.2352,642.0,-29902.0,-370.634,1369.536,92.4,16.463
2001-10-01,2.49,5.3,131452.0,3707.0,177.600,1.9,130.300,262862.0,8987.3,225.2,7212.9,171300.0,10660.465,88.4051,656.4,-30588.0,-369.688,1323.208,82.7,22.055
2002-01-01,1.73,5.7,130859.0,3699.0,177.700,1.2,128.500,250603.0,9015.6,441.6,7184.6,187100.0,10783.500,88.4634,670.1,-29678.0,-386.884,1356.041,93.0,16.523
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-01,5.33,3.9,157635.0,7619.0,313.016,2.8,256.978,595676.0,24511.1,1098.1,19603.3,415300.0,29016.714,102.3568,5742.1,-73110.0,-906.870,4061.192,77.2,16.529
2024-07-01,5.33,4.2,158003.0,7504.0,313.566,2.2,257.321,605797.0,24669.3,931.9,19866.3,429000.0,29374.914,102.5192,5752.2,-78639.0,-943.684,4163.975,66.4,16.347
2024-10-01,4.83,4.1,158358.0,7615.0,315.564,2.6,253.081,612570.0,24950.6,892.7,20123.2,426300.0,29723.864,102.2138,5772.2,-74250.0,-920.084,4141.013,70.5,16.581
2025-01-01,4.33,4.0,159053.0,7762.0,319.086,3.5,257.360,615973.0,25274.9,918.8,20370.0,429600.0,29962.047,102.8805,5779.4,-130273.0,-1245.141,4511.554,71.7,16.026
2025-04-01,4.33,4.2,159433.0,7395.0,320.321,2.5,258.369,623521.0,25823.5,1126.8,20622.3,413300.0,30331.117,103.6696,5821.7,-60257.0,-872.384,4114.330,52.2,17.741